### PR TITLE
This second commit is edited for sign-up page.

### PR DESCRIPTION
**Pull request by Mueenah1**
I edited the files with the right path to the referenced files. Picture files are now in the Pictures folder and logos are in the logo folder as well.

### CODE REVIEW

**Review by aanu444 — CHANGES_REQUESTED** [review]
Kindly rework this code...

**Review by Mueenah1 — COMMENTED** [review]
Changes have been made

**Review by bigkid-dev — APPROVED** [review]

**Review by bigkid-dev — APPROVED** [review]
Appreciate the commitment... lets go

**Review by bigkid-dev — APPROVED** [review]

**Review by aanu444 — APPROVED** [review]
This code is good to go.

**Pull request merged**
